// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEK17sX-5Xjijzjn319kTiiS_-gMnSdaE',
    appId: '1:598881097021:web:e3ac0dffb739b2abbb2154',
    messagingSenderId: '598881097021',
    projectId: 'sistem-kinerja-karyawan',
    authDomain: 'sistem-kinerja-karyawan.firebaseapp.com',
    storageBucket: 'sistem-kinerja-karyawan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALdb9nXtfLpWABzoD-nIp1k7tmUUL6Tbo',
    appId: '1:598881097021:android:d9899e9e478824f5bb2154',
    messagingSenderId: '598881097021',
    projectId: 'sistem-kinerja-karyawan',
    storageBucket: 'sistem-kinerja-karyawan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxIasVGu2s01AxhB2tLaPl8Dv9SOjE0eA',
    appId: '1:598881097021:ios:972ae0a4a8a8a810bb2154',
    messagingSenderId: '598881097021',
    projectId: 'sistem-kinerja-karyawan',
    storageBucket: 'sistem-kinerja-karyawan.firebasestorage.app',
    iosBundleId: 'com.example.sistemKinerja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxIasVGu2s01AxhB2tLaPl8Dv9SOjE0eA',
    appId: '1:598881097021:ios:972ae0a4a8a8a810bb2154',
    messagingSenderId: '598881097021',
    projectId: 'sistem-kinerja-karyawan',
    storageBucket: 'sistem-kinerja-karyawan.firebasestorage.app',
    iosBundleId: 'com.example.sistemKinerja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEK17sX-5Xjijzjn319kTiiS_-gMnSdaE',
    appId: '1:598881097021:web:613957589aa1d5aebb2154',
    messagingSenderId: '598881097021',
    projectId: 'sistem-kinerja-karyawan',
    authDomain: 'sistem-kinerja-karyawan.firebaseapp.com',
    storageBucket: 'sistem-kinerja-karyawan.firebasestorage.app',
  );
}
